'''
Created on Nov 25, 2012

@author: smotko
'''

if __name__ == '__main__':
    
    s = "CTACTCACTACTCATCTACTCACTACTCAGCTACTCACTACTCACTACTCAGGTTCTACTCACTACTCAATGTTCTACTCATCTACTCAATCTACTCACTACTCATACTACTCATTACATGTTACCTACTCATCTACTCAGGCTCGGCTACTCACTACTCAACTACTCACTACTCATATCTACTCATTCTACTCACTACTCATAGCTACTCACATCTACTCACCCTACTCAATGCCACTACTCACCTACTCACCTACTCACTACTCAATCTACTCACTACTCACTACTCAGCACCTACTCATGGCGCGCTACTCAGAGTCATATGCCTACTCAAAGCTACTCACTGACTACTCACGGGCCTACTCATTGTCTACTCATTCTACTCACTACTCACTACTCATTGGTACCTACTCAACTACTCAGATCTCCTACTCATCCCCACTACTCAACTACTCATCTACTCATCTACTCATCTACTCACTACTCATCTACTCAACTACTCATGCTCTACTCATAATCTACTCACGACTCTACTCACTTAACTACTCAGCTACTCACTACTCAGCGCGACTACTCAACTACTCACTACTACTCATCTACTCACGGTTCTACTCAAACTACTCACACAGTCTACTCAAATCTACTCACTACTCATGGCTACTCACTACTCACTACTCAAGCCGCTACTCACCTACTCAAACTACTCACTACTCACTACTCAACCCCGGGCTACTCAGCTACTCAGCAACTACTCAAACTACTCATGTACTACTCATCTACTCACTACTCACTACTCACGCCTACTCACTACTCAACTACTCACTACTCACTACTCA"
    sb = "CTACTCACT"
    strs = []
    for i in range(len(s)):
        
        if s[i:i+len(sb)] == sb:
            strs.append(str(i+1))
    
    print " ".join(strs)
